version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Europe/London
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.30
    - 14.14.34
    - 15.0.0
  - dependency-name: runtypes
    versions:
    - 6.0.0
    - 6.1.0
    - 6.2.1
  - dependency-name: "@sentry/browser"
    versions:
    - 6.2.3
  - dependency-name: yup
    versions:
    - 0.32.9
  - dependency-name: option-t
    versions:
    - 25.0.2
  - dependency-name: react-use
    versions:
    - 17.0.1
    - 17.1.0
