version: "3.8"

services:
  mongo:
    container_name: pubg-mongo
    image: mongo
    restart: unless-stopped
    networks:
      - pubg-network
    volumes:
      - mongo-data:/data/db

  redis:
    container_name: pubg-redis
    image: redis:alpine
    restart: unless-stopped
    networks:
      - pubg-network
    volumes:
      - redis-data:/data
      - redis-dump:/var/lib/redis

  server:
    container_name: pubg-server
    build: .
    environment:
      - REDIS_HOST=redis://pubg-redis
      - MONGO_HOST=mongodb://mongo:27017/pubg-mongo
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
    networks:
      - pubg-network
    ports:
      - ${PORT}:${PORT}

networks:
  pubg-network:
    driver: bridge

volumes:
  mongo-data:
  redis-data:
  redis-dump:
