version: "3"

services:
  redis:
    container_name: pubg-redis
    image: redis:alpine
    restart: always
    networks:
      - pubg-network
    volumes:
      - redis-data:/data
      - redis-dump:/var/lib/redis
    # ports:
    #   - 6379:6379

  mongo:
    container_name: pubg-mongo
    image: mongo
    networks:
      - pubg-network
    volumes:
      - mongo-data:/data/db
    # ports:
    #   - 27017:27017

  server:
    container_name: pubg-server
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - PORT=${PORT}
      - CLIENT_ORIGIN=${CLIENT_ORIGIN}
      - REDIS_HOST=redis://pubg-redis
      - MONGO_HOST=mongodb://mongo:27017/pubg-mongo
      - PUBG_API_TOKEN=${PUBG_API_TOKEN}
    depends_on:
      - redis
      - mongo
    ports:
      - ${PORT}:${PORT}
    # volumes:
    #   - server-data:/usr/src/app
    networks:
      - pubg-network

networks:
  pubg-network:
    driver: bridge

volumes:
  mongo-data:
  redis-data:
  redis-dump:
